/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicHooksRefreshPricesRouteImport } from './routes/api/public/hooks/refresh-prices'
import { Route as ApiPublicHooksCuelinksPostbackRouteImport } from './routes/api/public/hooks/cuelinks-postback'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshPricesRoute =
  ApiPublicHooksRefreshPricesRouteImport.update({
    id: '/api/public/hooks/refresh-prices',
    path: '/api/public/hooks/refresh-prices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCuelinksPostbackRoute =
  ApiPublicHooksCuelinksPostbackRouteImport.update({
    id: '/api/public/hooks/cuelinks-postback',
    path: '/api/public/hooks/cuelinks-postback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/disclosure': typeof DisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/hooks/cuelinks-postback': typeof ApiPublicHooksCuelinksPostbackRoute
  '/api/public/hooks/refresh-prices': typeof ApiPublicHooksRefreshPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/disclosure': typeof DisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/hooks/cuelinks-postback': typeof ApiPublicHooksCuelinksPostbackRoute
  '/api/public/hooks/refresh-prices': typeof ApiPublicHooksRefreshPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/disclosure': typeof DisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/hooks/cuelinks-postback': typeof ApiPublicHooksCuelinksPostbackRoute
  '/api/public/hooks/refresh-prices': typeof ApiPublicHooksRefreshPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/categories'
    | '/coupons'
    | '/disclosure'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/wallet'
    | '/product/$id'
    | '/api/public/hooks/cuelinks-postback'
    | '/api/public/hooks/refresh-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/categories'
    | '/coupons'
    | '/disclosure'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/wallet'
    | '/product/$id'
    | '/api/public/hooks/cuelinks-postback'
    | '/api/public/hooks/refresh-prices'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/categories'
    | '/coupons'
    | '/disclosure'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/wallet'
    | '/product/$id'
    | '/api/public/hooks/cuelinks-postback'
    | '/api/public/hooks/refresh-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CategoriesRoute: typeof CategoriesRoute
  CouponsRoute: typeof CouponsRoute
  DisclosureRoute: typeof DisclosureRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicHooksCuelinksPostbackRoute: typeof ApiPublicHooksCuelinksPostbackRoute
  ApiPublicHooksRefreshPricesRoute: typeof ApiPublicHooksRefreshPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-prices': {
      id: '/api/public/hooks/refresh-prices'
      path: '/api/public/hooks/refresh-prices'
      fullPath: '/api/public/hooks/refresh-prices'
      preLoaderRoute: typeof ApiPublicHooksRefreshPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cuelinks-postback': {
      id: '/api/public/hooks/cuelinks-postback'
      path: '/api/public/hooks/cuelinks-postback'
      fullPath: '/api/public/hooks/cuelinks-postback'
      preLoaderRoute: typeof ApiPublicHooksCuelinksPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CategoriesRoute: CategoriesRoute,
  CouponsRoute: CouponsRoute,
  DisclosureRoute: DisclosureRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicHooksCuelinksPostbackRoute: ApiPublicHooksCuelinksPostbackRoute,
  ApiPublicHooksRefreshPricesRoute: ApiPublicHooksRefreshPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
